Reset the admin on access back to the API study
Sage-Bionetworks/BridgeIntegTestUtils pull request #4
Opened 2018-09-20 23:56 UTC by alxdarksage

2018-10-02 22:15 UTC, DwayneJengSage requested changes

2018-10-02 22:15 UTC, DwayneJengSage commented on src/main/java/org/sagebionetworks/bridge/user/TestUserHelper.java
> +        String testStudyId = CONFIG.fromProperty(Config.Props.API_DEVELOPER_STUDY);
API_DEVELOPER_STUDY is going to be removed, as per https://sagebionetworks.jira.com/browse/BRIDGE-2086

The canonical config for the API study is Props.STUDY_IDENTIFIER

2018-10-03 21:21 UTC, alxdarksage commented
Updated to STUDY_IDENTIFIER constant.

2018-10-03 21:37 UTC, DwayneJengSage approved these changes

2018-10-03 22:42 UTC, merged